language: bash
sudo: required
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.20.0
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - docker
before_install:
- openssl aes-256-cbc -K $encrypted_746fc4fff1b7_key -iv $encrypted_746fc4fff1b7_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud version
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
- if [[ -z "${TRAVIS_TAG}" ]]; then TAG=v${TRAVIS_BUILD_NUMBER}; else TAG=${TRAVIS_TAG};
  fi
install:
- gcloud config set project easyship-test
- gcloud config set compute/zone us-east1-b
- gcloud -q components install kubectl
- gcloud container clusters get-credentials cluster-1
before_script:
- cp config/database.yml.example config/database.yml
- if [ -f docker/image.tar.gz ];then gzip -dc docker/image.tar.gz | docker load; fi
- docker build -f Dockerfile.devel -t rails_4_travis:latest 
- docker save rails_4_travis:latest | gzip > docker/image.tar.gz
script:
- docker tag rails_4_travis:latest us.gcr.io/easyship-test/rails_4_travis:${TAG}
- gcloud docker -- push us.gcr.io/easyship-test/rails_4_travis:${TAG}
- docker-compose run test
after_success:
- | 
  cat rails-db-migrate-job.yaml.tmpl | \
  sed 's/\$IMAGE'"/us.gcr.io\/easyship-test\/rails_4_travis:${TAG}/g" | \
  kubectl apply -f -
- |
    kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | \
    grep rails-db-migrate   
- |
  kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | \
  grep rails-db-migrate | \ 
  xargs -i kubectl attach -it {}
- kubectl delete job rails-db-migrate
- kubectl set image deployment rails-4-travis rails-4-travis=us.gcr.io/easyship-test/rails_4_travis:${TAG}