steps:
  - name: 'ubuntu'
    args: ['bash','-c', 'if [ $BRANCH_NAME != "${_BRANCH}" ];then echo "Branch mismatch!!";exit 1; fi']
  - name: 'ubuntu'
    args: ['bash','-c', 'cp config/database.yml.example config/database.yml']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f','Dockerfile.devel','-t', '${_REPO}/$PROJECT_ID/${_PROJECT}:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_REPO}/$PROJECT_ID/${_PROJECT}:v1', '${_PROJECT}:latest']    
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['run','test']      
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_REPO}/$PROJECT_ID/${_PROJECT}:v1']  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud components install kubectl
      gcloud container clusters get-credentials ${_CLUSTER} --zone ${_ZONE}
      kubectl delete job rails-db-migrate || true
      cat rails-db-migrate-job.yaml.tmpl | sed 's/IMAGE'"/${_REPO}\/$PROJECT_ID\/${_PROJECT}:v1/g" | kubectl apply -f -
      until kubectl get po -a | grep rails-db-migrate | grep Completed;
      do
        sleep 1;
        COUNTER=`expr $COUNTER - 1`;
        if [ $COUNTER -eq 0 ]; then exit 1; fi
      done
      kubectl logs -f $(kubectl get po -a | grep rails-db-migrate | awk {'print $1'})      
      kubectl set image deployment ${_PROJECT} ${_PROJECT}=${_REPO}/$PROJECT_ID/${_PROJECT}:v1  
      kubectl rollout status deployment ${_PROJECT}
    env:
      COUNTER=600
images: ["${_REPO}/$PROJECT_ID/${_PROJECT}:v1"]  
substitutions:
  _PROJECT: rails-4-travis
  _REPO: us.gcr.io
  _ZONE: us-east1-b
  _CLUSTER: cluster-1
  _BRANCH: master