version: '3'
services:
  test:
    tty: true
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.devel
    image: rails-4-travis:latest
    command: sh -c "bundle exec rake db:migrate && bundle exec rake db:test:prepare && bundle exec rspec spec/"
    volumes:
      - .:/app